### ISSUE TITLE
Validating Offsets

### ISSUE THREAD

**Issue by gr3atest** [jsherman212/xnuspy#3]
I attempted to reproduce the results for `open1_hook` but my device kept panicing, which is most likely due to my offset being `open` offset being wrong. I tried to reproduce the offsets you came up with:

```
iPhone X 13.3.1:        0xfffffff007d70534
iPhone 8 13.6.1:        0xfffffff007d99c1c
iPhone 7 14.1:          0xfffffff00730aa64
iPhone SE (2016) 14.3:  0xfffffff0072da190
```

By downloading IPSW for those devices, and I kept getting different offsets (`open: 0x17fff007d710e4` for iPhone X 13.3.1). I used `joker -s` once I decrypted & decompressed the kernel cache. The assumptions I made are:

1. You retrieved the these addresses by looking into the decrypted kernelchache associated with the correct device
2. When you mention "open1", you're referring to the "open" syscall

Please let me know if I'm missing anything/or if you have any guidance on extracting the right offset. Thanks in advance!

**Comment by jsherman212** [comment]
Hey! The offset you are getting with the `17` in the top bits is a tag (https://bazad.github.io/2018/06/ios-12-kernelcache-tagged-pointers/) and can be safely replaced with the normal `ffff` for use with xnuspy. So your first assumption is correct, but your second assumption isn't. I am referring to `open1`, not `open`. The reason I'm not hooking `open` is because there are a few other system calls which can be used to open a file, like `open_dprotected_np`, `open_extended`, or `open_nocancel`. All of these system calls eventually lead to `open1`, so by hooking `open1` instead of `open`, I can account for the other open-like system calls without actually having to hook them.

The offset joker gave you for `open` is correct if you replace `17` with `ffff`. But again, that's the offset for `open` and we need `open1`. If you scroll down near `open`'s epilogue, you'll see it call a function with a function pointer argument put inside `X4`. That's `open1`. In the screenshot below I've already renamed this function to `open1`:

<img width="876" alt="TEXT EXEC textFFFFFFF007D712B8 loc_FFFFFFF007D712B8" src="https://user-images.githubusercontent.com/42921048/107157466-3ad1e100-6952-11eb-91f7-1fe5d6210cd4.png">

By the way, what device/iOS version are you trying to use xnuspy with? I can look into the offset of `open1` for your kernel if you're having trouble finding it.

**Comment by gr3atest** [comment]
Legendary! That makes perfect sense. You went another layer deeper into the syscalls, brilliant. Thanks for the reference for the tag pointers as well. Once I followed your steps, I was able to see how you derived with those addresses and I was also able to derive it for my platform (iPhone 7 - iOS 13.3.1: `0xfffffff0072bb328`). 

Thanks a ton, this was incredibly helpful!
